### PR TITLE
"Titles" refactor

### PR DESCRIPTION
**Pull request by beardypig**
Hey @Hubcapp, I think it's actually easier if I just open a PR to give you my fixes :) 

On Linux and macOS it doesn't look like you need to encode any unicode arguments - `subprocess` appears to handle it correctly. I tested with Python 2 and Python 3.

I have also improved the `supported_player` method so that it better detects the players and doesn't give false positives.

The only thing that needs more work is the `test_open_player_with_unicode_author_vlc` method in the Windows tests. I need to install Python 2 on my Windows box and test it there. I only tested on Windows with Python 3 - it works great though :)

### CODE REVIEW

**Comment by Hubcapp** [comment]
Thanks for this, looks great. I've tested on Windows 7 Python 3 (it actually gets the correct unicode characters in the player's title, I guess because of better integration with the Windows Unicode API) and on Windows 10 Python 2.

Here's some old photos from earlier today before implementing LazyFormatter, so you know about what to expect:

Windows 10 Python 2 using mbcs encoding (current behavior):


Windows 10 Python 2 using utf-8 encoding (tried this before using mbcs encoding):


Windows 7 Python 3 using Python 3's native unicode support:


I'll merge when you're done. I'm not currently doing anything with it, so no need to worry about merge conflicts.

**Comment by beardypig** [comment]
@Hubcapp I updated the tests, they should all pass now. I see what the problem with the encoding in Windows Python 2 is, it's not very simple to fix - and I don't think it's worth it. Most of the Windows users will be using the installer or portable versions which are based on Python 3.

**Comment by beardypig** [comment]
There is still an issue with the tests, the documentation fails to build - but I cannot work out what the error means :D

**Comment by Hubcapp** [comment]
I have no clue about that documentation failure under only appveyor's Python 3.5 test. The only documentation I touched was probably the section ending in

`        """.format( ', '.join(SUPPORTED_PLAYERS.keys()),
                    DEFAULT_STREAM_METADATA['title'],
                    DEFAULT_STREAM_METADATA['author'],
                    DEFAULT_STREAM_METADATA['category'])`

**Comment by beardypig** [comment]
Yeah, it must be that -  the error is

```text
/streamlink/docs/cli.rst:281:Definition list ends without a blank line; unexpected unindent.
```

Which is a bit cryptic :)

**Comment by beardypig** [comment]
OK, fixed it now. 

The docs probably need a bit of work - they don't explain that you can use formatting variables in the custom title. See the docs for `--player-args`.

**Comment by beardypig** [comment]
I'm done for now @Hubcapp, I did leave you some work to do though :p

**Pull request merged**
